repos:

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy
    args: [--scripts-are-modules, --explicit-package-bases]
    additional_dependencies:
    - types-python-dateutil
    - types-pyyaml
    - types-requests
    - types-toml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.1
  hooks:
  - id: ruff
