#!/bin/bash
echo 'Deprecated - this script is going to get removed in a few days.'
exit 1

#basic stuff
    pushd $dir >/dev/null
    echo 'Updating git submodules...'
    git submodule init
    git submodule update
    popd >/dev/null

#python
    if $cygwin; then
        install_cygwin python
        install_cygwin python3
    elif $linux; then
        install_pacman python
        install_pacman python-pip
    fi

#zsh
    if $cygwin; then
        install_cygwin zsh
    elif $linux; then
        install_pacman zsh
    fi
    if has_installed zsh; then
        install_link "$dir/.zshrc" "$HOME/.zshrc"
    fi

#terminal emulators
    if has_installed mintty; then
        install_link "$dir/.inputrc" "$HOME/.inputrc"
        install_link "$dir/.minttyrc-light" "$HOME/.minttyrc"
    fi

#translator
    install_link "$dir/ext/translator/tl" "$dir/bin/ext/tl"
