#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

git submodule init
git submodule update

function install_link {
	source=$1
	target=$2
	use_sudo=$3

	echo "Installing $source to $target"

	if [ -h "$target" ]; then
		echo Removing old symlink "$target"
		if [ $use_sudo ]; then
			sudo rm "$target"
		else
			rm "$target"
		fi
	else
		if [ -e "$target" ]; then
			echo Not a symlink: "$target". Aborting.
			exit 1
		fi
	fi

	if [ $use_sudo ]; then
		sudo ln -s "$source" "$target"
	else
		ln -s "$source" "$target"
	fi
}

fonts_dir=/usr/share/fonts/TTF
if [ -d $fonts_dir ]; then
	for x in $DIR/misc/*.ttf; do
		install_link "$x" "$fonts_dir/$(basename "$x")" 1
	done
	fc-cache -fv
fi

[ ! -d "$HOME/.vim" ] && mkdir "$HOME/.vim"
[ ! -d "$HOME/.vim/undo" ] && mkdir "$HOME/.vim/undo"
[ ! -d "$HOME/.vim/backup" ] && mkdir "$HOME/.vim/backup"
[ ! -d "$HOME/.vim/swap" ] && mkdir "$HOME/.vim/swap"
[ ! -d "$HOME/.vim/spell" ] && mkdir "$HOME/.vim/spell"

install_link "$DIR/ext/translator/tl"       "$DIR/bin/ext/tl"
install_link "$DIR/.vim/spell/pl.utf-8.add" "$HOME/.vim/spell/pl.utf-8.add"
install_link "$DIR/.vim/spell/en.utf-8.add" "$HOME/.vim/spell/en.utf-8.add"
install_link "$DIR/.vim/vundle"             "$HOME/.vim/vundle"
install_link "$DIR/.vimrc"                  "$HOME/.vimrc"
install_link "$DIR/.zshrc"                  "$HOME/.zshrc"
install_link "$DIR/.bashrc"                 "$HOME/.bashrc"
install_link "$DIR/.inputrc"                "$HOME/.inputrc"
install_link "$DIR/.minttyrc-light"         "$HOME/.minttyrc"
install_link "$DIR/.gitconfig"              "$HOME/.gitconfig"
install_link "$DIR/.gitignore"              "$HOME/.gitignore"
install_link "$DIR/.mpv"                    "$HOME/.mpv"
install_link "$DIR/.i3"                     "$HOME/.i3"
install_link "$DIR/.Xresources"             "$HOME/.Xresources"

shopt -s nocasematch
if [[ "$(uname)" =~ cygwin ]]; then
	cd "$HOME"
	echo "Hiding dotfiles in $HOME"
	attrib +h +s .\*
fi
