if [ -z "$SSH_CLIENT" ] && [ -z "$SSH_CONNECTION" ]; then
    if command -v startx &>/dev/null; then
        [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
    else
        echo 'startx not found'
    fi
fi
