#!/usr/bin/env python3
from pathlib import Path
from subprocess import run


def main():
    config_dir = Path("~/.config/mpvmd").expanduser()
    run(["mpv", f"--config-dir={config_dir}"])


if __name__ == "__main__":
    main()
