#!/bin/sh

# installs apt-cyg for cygwin.

git clone https://github.com/kou1okada/apt-cyg /usr/local/share/apt-cyg
ln -s /usr/local/share/apt-cyg/apt-cyg /usr/local/bin/apt-cyg

/usr/local/bin/apt-cyg update -m 'http://mirrors.kernel.org/sources.redhat.com/cygwin/'
/usr/local/bin/apt-cyg update -m 'http://mirrors.kernel.org/sources.redhat.com/cygwinports/'
