#!/bin/sh

# installs apt-cyg for cygwin.

lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg
install apt-cyg /bin

/bin/apt-cyg update -m 'http://mirrors.kernel.org/sources.redhat.com/cygwin/'
/bin/apt-cyg update -m 'http://mirrors.kernel.org/sources.redhat.com/cygwinports/'
