#!/bin/sh

# installs pip for cygwin.

lynx -source https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py >ez_setup
chmod +x ez_setup
./ez_setup

apt-cyg install python-setuptools
apt-cyg install python3-setuptools
easy_install-3.4 pip

rm ez_setup
rm setuptools-*.zip
