#!/bin/sh
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 IM

global_config() {
    bspc config $1 $2
}
monitor_config() {
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}
desktop_config() {
    for D in $(bspc query -D); do
        bspc config -d $D $1 $2
    done
}
run_if_needed() {
    name=$1; shift
    if ! xdotool search --name "$name"; then
        nohup $@ </dev/null &>/dev/null &
    fi
}

global_config focused_border_color "#00d0ee"
global_config urgent_border_color "#de3333"
global_config active_border_color "#bbbbbb"
global_config normal_border_color "#bbbbbb"

monitor_config top_padding 19
monitor_config right_padding 0
monitor_config bottom_padding 0
monitor_config left_padding 0

desktop_config top_padding 0
desktop_config right_padding 0
desktop_config bottom_padding 0
desktop_config left_padding 0

desktop_config border_width 4
desktop_config window_gap 0
global_config split_ratio             0.6
global_config borderless_monocle      true
global_config gapless_monocle         true
global_config focus_by_distance       true
global_config focus_follows_pointer   true

bspc rule -a remote_irc desktop=IM
bspc rule -a qbittorrent desktop=9
bspc rule -a Steam desktop=8
bspc config external_rules_command "$DIR/rules"

pkill -f sxhkd
sxhkd &

# fix Java GUI rendering - found in baskerville's dotfiles
IRONIC_WM_NAME="LG3D"
NET_WIN=$(xprop -root _NET_SUPPORTING_WM_CHECK | awk -F "# " '{print $2}')
if [[ "$NET_WIN" == 0x* ]]; then
    xprop -id "$NET_WIN" -remove _NET_WM_NAME
    xprop -id "$NET_WIN" -f _NET_WM_NAME 8s -set _NET_WM_NAME "$IRONIC_WM_NAME"
else
    xprop -root -remove _NET_WM_NAME
    xprop -root -f _NET_WM_NAME 8s -set _NET_WM_NAME "$IRONIC_WM_NAME"
fi

pkill -f .config/panel
nohup ~/.config/panel </dev/null &>/dev/null &
if [ -e ~/.config/zsh/lightness.sh ]; then
    . ~/.config/zsh/lightness.sh
    ~/src/dotfiles/bin/util/lightness $LIGHTNESS
fi
