#!/bin/python3
from subprocess import run, PIPE

GAP_PADDING = 25
TOP, RIGHT, BOTTOM, LEFT = range(4)
DIRECTIONS = {TOP: 'top', RIGHT: 'right', BOTTOM: 'bottom', LEFT: 'left'}


def bspc(command):
    return run(['bspc'] + command, stdout=PIPE).stdout.decode()


def main():
    monitor = bspc(['query', '-D', '-n']).strip()
    paddings = {}
    for dir, name in DIRECTIONS.items():
        paddings[dir] = \
            int(bspc(['config', '-d', monitor, '%s_padding' % name]))

    panel_sizes = {
        TOP:    paddings[TOP] - paddings[LEFT],
        BOTTOM: paddings[BOTTOM] - paddings[LEFT],
    }

    target_padding = 0 if paddings[LEFT] > 0 else GAP_PADDING
    target_paddings = {
        TOP:    panel_sizes[TOP] + target_padding,
        BOTTOM: panel_sizes[BOTTOM] + target_padding,
        LEFT:   target_padding,
        RIGHT:  target_padding,
    }

    for dir, padding in target_paddings.items():
        name = DIRECTIONS[dir]
        bspc(['config', '-d', monitor, '%s_padding' % name, str(padding)])


if __name__ == '__main__':
    main()
