#!/bin/python3
from plumbum import local

gap_padding = 25

TOP, RIGHT, BOTTOM, LEFT = range(4)
directions = {TOP: 'top', RIGHT: 'right', BOTTOM: 'bottom', LEFT: 'left'}

bspc = local['bspc']

monitor = bspc(['query', '-D', '-n']).strip()
paddings = {}
for dir, name in directions.items():
    paddings[dir] = int(bspc(['config', '-d', monitor, '%s_padding' % name]))

panel_sizes = {
    TOP:    paddings[TOP] - paddings[LEFT],
    BOTTOM: paddings[BOTTOM] - paddings[LEFT],
}

target_padding = 0 if paddings[LEFT] > 0 else gap_padding
target_paddings = {
    TOP:    panel_sizes[TOP] + target_padding,
    BOTTOM: panel_sizes[BOTTOM] + target_padding,
    LEFT:   target_padding,
    RIGHT:  target_padding,
}

for dir, padding in target_paddings.items():
    name = directions[dir]
    bspc(['config', '-d', monitor, '%s_padding' % name, padding])
