class ColorsDark:
    background = '#000'
    foreground = '#CCC'
    workspace_background = '#111'
    workspace_border = '#666'
    workspace_full_background = '#555'
    workspace_full_border = '#666'
    workspace_focused_background = '#530'
    workspace_focused_border = '#B70'
    workspace_focused_full_background = '#C60'
    workspace_focused_full_border = '#F80'
    workspace_urgent_background = '#D44465'
    workspace_urgent_border = '#AB096B'
    chart_background = '#111'
    chart_foreground = '#666'
    cpu_chart_line = '#F00'
    net_up_chart_line = '#0B0'
    net_down_chart_line = '#F00'
    volume_chart_background = '#AAA'


class ColorsLight:
    background = '#CCC'
    foreground = '#333'
    workspace_background = '#EEE'
    workspace_border = '#888'
    workspace_full_background = '#AAA'
    workspace_full_border = '#888'
    workspace_focused_background = '#FFDFA1'
    workspace_focused_border = '#B84'
    workspace_focused_full_background = '#FA0'
    workspace_focused_full_border = '#A50'
    workspace_urgent_background = '#F99CB1'
    workspace_urgent_border = '#DD4000'
    chart_background = '#EEE'
    chart_foreground = '#888'
    cpu_chart_line = '#F00'
    net_up_chart_line = '#0B0'
    net_down_chart_line = '#F00'
    volume_chart_background = '#AAA'


Colors = ColorsDark
