#!/usr/bin/env python3
import socket
from pathlib import Path
from subprocess import check_output, run
from typing import TypedDict

from libdotfiles import logging
from libdotfiles.util import HOME_DIR

try:
    import yaml
except ImportError:
    yaml = None

SESSIONS_PATH = HOME_DIR / ".config/tmux/sessions.yml"


class WindowSpec(TypedDict):
    window_name: str
    cwd: str


class SessionSpec(TypedDict):
    name: str
    windows: list[WindowSpec]


Spec = list[SessionSpec]


def renumber_sessions() -> None:
    """Make sure that numeric sessions names appear in linear order."""
    session_names = run(
        ["tmux", "list-sessions", "-F", "#S"], capture_output=True, text=True
    ).stdout.splitlines()
    numeric_sessions = [int(name) for name in session_names if name.isdigit()]
    for new_name, old_name in enumerate(numeric_sessions, 1):
        run(["tmux", "rename", "-t", str(old_name), str(new_name)])


def recreate_session(spec: SessionSpec) -> None:
    result = run(
        [
            "tmux",
            "new-session",
            "-d",
            "-s",
            spec["name"],
            "-c",
            Path(spec["windows"][0]["cwd"]).expanduser(),
        ]
    )

    created = result.returncode == 0
    existing_windows = check_output(
        ["tmux", "list-windows", "-t", spec["name"], "-F", "#{window_name}"],
        text=True,
    ).splitlines()

    for window in reversed(spec["windows"]):
        if window["window_name"] not in existing_windows:
            run(
                [
                    "tmux",
                    "new-window",
                    "-d",
                    "-a",
                    "-t",
                    spec["name"] + ":" + existing_windows[0],
                    "-n",
                    window["window_name"],
                    "-c",
                    Path(window["cwd"]).expanduser(),
                ]
            )

    if created:
        run(
            [
                "tmux",
                "kill-window",
                "-t",
                spec["name"] + ":" + existing_windows[0],
            ]
        )


def recreate_sessions() -> None:
    """Recreate sessions that should be persisted across machines."""
    if not yaml:
        logging.warn("pyyaml module not installed")
        return
    if not SESSIONS_PATH.exists():
        logging.warn("sessions file does not exist")
        return

    config = yaml.safe_load(SESSIONS_PATH.read_text())
    machine_name = socket.gethostname()

    specs = config.get(machine_name, [])
    for spec in specs:
        recreate_session(spec)


def main() -> None:
    renumber_sessions()
    recreate_sessions()


if __name__ == "__main__":
    main()
