SOURCE=$(readlink ${(%):-%N})
DIR=${SOURCE:h:h:h}

# path
setopt NO_NOMATCH
path=(/usr/local/bin $path)             # prefer manually compiled libraries
path=(~/.local/bin/ $path)              # python!
path=(~/.local/bin-priv/ $path)         # python!
path=($DIR/bin/* $path)                 # PATH for all the goodies in this repo
export PATH                             # export modified var for subprocesses

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT4_IM_MODULE=fcitx
export CLUTTER_IM_MODULE=fcitx

export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:$LD_LIBRARY_PATH
export INCLUDE_PATH=/usr/local/include:/usr/include:$INCLUDE_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/lib/pkgconfig:$PKG_CONFIG_PATH

export PYTHONPYCACHEPREFIX=/tmp/pycache
export TZ='Europe/Warsaw'

# fix gpg not working in ssh…
export GPG_TTY=$(tty)
