SOURCE=$(readlink ${(%):-%N})
DIR=${SOURCE:h:h:h}

# path
setopt NO_NOMATCH
path=(~/.local/bin/ $path)              # python!
path=(~/.gem/ruby/*/bin $path)          # ruby!
path=(/usr/local/bin $path)             # prefer manually compiled libraries
path=($DIR/bin/* $path)                 # PATH for all the goodies in this repo
export PATH                             # export modified var for subprocesses

export LD_LIBRARY_PATH=/usr/local/lib

typeset -T PYTHONPATH pythonpath :      # turn PYTHONPATH into zsh list
if [ -d $DIR/lib ]; then                # shared libraries for Python scripts
    pythonpath=($DIR/lib/)
fi
export PYTHONPATH                       # export modified var for subprocesses
