SOURCE=$(readlink ${(%):-%N})
DIR=${SOURCE:h:h:h}

# path
setopt NO_NOMATCH
path=(/usr/local/bin $path)             # prefer manually compiled libraries
path=(~/.local/bin/ $path)              # python!
path=($DIR/bin/* $path)                 # PATH for all the goodies in this repo
export PATH                             # export modified var for subprocesses

export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
export INCLUDE_PATH=/usr/local/include:$INCLUDE_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH

typeset -T PYTHONPATH pythonpath :      # turn PYTHONPATH into zsh list
if [ -d $DIR/lib ]; then                # shared libraries for Python scripts
    pythonpath=($DIR/lib/)
fi
export PYTHONPATH                       # export modified var for subprocesses
