# aliases related to colors
if whence -p dircolors >/dev/null; then
    eval `dircolors`
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# aliases
alias p=python3.10
alias pi=ipython3
alias l="myls"
alias ll="myls -l"
alias la="myls -la"
alias e='vifm'
alias v='nvim'
alias g='command git'
    alias gd='command git diff'
    alias gs='command git status'
    alias gsh='command git show'
    alias ghis='command git hist'
    alias ga='command git add'
    alias gam='command git amen'
    alias gamp='command git amen -p'
    alias gap='command git add -p'
    alias gau='command git add -u'
    alias gc='command git commit'
    alias gch='command git checkout'
    alias gpl='command git pull'
    alias gps='command git push'
    alias gb='command git branch'
    alias gres='command git reset'
    alias gr='command git rebase'
    alias gri='command git rebase -i'
    alias grc='command git rebase --continue'
alias w='work'
jisho() { command jisho "$@"|less -rFX }
edict() { command edict "$@"|less -rFX }
tl() {
    source="$1"; shift
    target="$1"; shift
    trans -s "$source" -t "$target" "$@"|less -rFX
}
alias plen='tl pl en'
alias enpl='tl en pl'
alias enja='tl en ja'
alias jaen='tl ja en'

alias track-moto='p -m timetracker moto'
alias track-ng='p -m timetracker netguru'

alias pyup='pip install --user --upgrade --no-deps .'

alias reverso='p -m dict -e reverso'
alias urban='p -m dict -e urban'
alias sjp='p -m dict -e sjp'
alias jisho='p -m dict -e jisho'
alias wordhippo='p -m dict -e wordhippo'
alias synonim='p -m dict -e synonim'
alias edict='p -m dict -e edict'
alias jmdict='p -m dict -e jmdict'

alias dl-gelbooru='dl-booru --config=~/.config/dl-gelbooru.conf'
alias dl-pixiv='dl-booru --config=~/.config/dl-pixiv.conf'
alias dl-yume='dl-booru --config=~/.config/dl-yume.conf'
alias ul-gelbooru='ul-booru --config=~/.config/ul-gelbooru.conf'
alias ul-yume='ul-booru --config=~/.config/ul-yume.conf'
alias tmp=ul-tmp
alias 0x0=ul-0x0

alias pw='aes-edit ~/.config/pw.dat'

vb() {
    dec vm
    vboxsdl --startvm $(VBoxManage list vms |pcregrep -o1 '(?:")(.*)(?:")') &
    disown
}

# legacy aliases
command -v hd >/dev/null 2>&1 || alias hd='od -Ax -t x1'
if ! command -v poweroff >/dev/null 2>&1; then
    [[ $(uname) =~ cygwin ]] && alias poweroff='shutdown /p /f' || alias poweroff='shutdown -s now'
fi
if ! command -v reboot >/dev/null 2>&1; then
    [[ $(uname) =~ cygwin ]] && alias reboot='shutdown /r /t 0 /f' || alias reboot='shutdown -r now'
fi

# colorful manpages
man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}

# extend docker capabilities
docker() {
    case "$1" in
    kill-all)
        command docker kill $(command docker ps -q)
        ;;
    *)
        command docker "$@"
    esac
}

# load additional modules
for x in ~/.config/zsh/*.sh; do
    source "$x"
done &>/dev/null
