if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
fi

for f in ~/.config/Xresources*; do
    xrdb -override "$f"
done

#left pointing cursor
xsetroot -cursor_name left_ptr

#set Polish keyboard
setxkbmap pl

clipit -d &
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

[ -d ~/.config/x ] && for x in ~/.config/x/*.sh; do
    [ -x "$x" ] && . "$x"
done
