if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xrdb ~/.config/Xresources
xrdb -override ~/.config/Xresources-theme

#left pointing cursor
xsetroot -cursor_name left_ptr

#set Polish keyboard
kb pl

clipit -d &
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

[ -d ~/.config/x ] && for x in ~/.config/x/*.sh; do
    [ -x "$x" ] && . "$x"
done
