#! /bin/sh

desktop_config() {
    bspc config $1 $2
    for M in $(bspc query -M); do
        bspc config -m $M $1 $2
    done
}
run_if_needed() {
    xdotool search --name "$1" &>/dev/null || nohup "$2" </dev/null &>/dev/null &
}


desktop_config focused_border_color "#748FA4"
desktop_config urgent_border_color "#DE3333"
desktop_config active_border_color "#333333"
desktop_config normal_border_color "#333333"

desktop_config top_padding 19
desktop_config border_width 3
desktop_config window_gap 12
desktop_config split_ratio             0.50
desktop_config borderless_monocle      true
desktop_config gapless_monocle         true
desktop_config focus_by_distance       true
desktop_config focus_follows_pointer   true

if [ "$(hostname)" = tornado ]; then
    bspc monitor HDMI-0 -d 1 2
    bspc monitor DVI-I-1 -d 3 4 5 6 7 8 9 10 IM
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10 IM
fi

#TODO
bspc rule -a Buddy desktop=IM
bspc rule -a Pidgin desktop=IM floating=on
bspc rule -a Trackma-qt desktop=10 floating=on
bspc rule -a music_player desktop=10 floating=on
bspc rule -a qbittorrent desktop=9
bspc rule -a Steam desktop=8
bspc rule -a mpv desktop=1

pkill -f bspwm/panel
nohup $HOME/.config/bspwm/panel </dev/null &>$HOME/.debug/panel &

if [ "$(hostname)" = tornado ]; then
    run_if_needed pidgin pidgin
    run_if_needed firefox firefox
    run_if_needed trackma-qt trackma-qt
    run_if_needed qbittorrent qbittorrent
elif [ "$(hostname)" = chibi ]; then
    run_if_needed trackma-qt trackma-qt
fi
