#!/bin/sh
bspc query -T | grep '[f-][d-][F][u-][l-][s-][i-][p-]' &>/dev/null
xdo below -t "$(xdo id)" "$(xdo id -n panel)"
if [ "$?" == '0' ]; then
    bspc window -t fullscreen -l normal
else
    bspc window -t fullscreen -l above
fi
