class ColorsDark:
    background = "#000000"
    foreground = "#CCC"
    workspace_background = "#111"
    workspace_foreground = "#555"
    workspace_full_background = "#333"
    workspace_full_foreground = "#CCC"
    workspace_focused_background = "#003241"
    workspace_focused_foreground = "#CDE"
    workspace_focused_full_background = "#027BB2"
    workspace_focused_full_foreground = "#CDE"
    workspace_urgent_background = "#FF8000"
    workspace_urgent_foreground = "#000000"
    chart_background = "#222"
    chart_foreground = "#888"
    cpu_chart_line = "#C60"
    currency_chart_line = "#08C"
    memory_chart_line = "#F80"
    net_up_chart_line = "#0B0"
    net_down_chart_line = "#F00"
    volume_chart_background = "#AAA"


class ColorsLight:
    background = "#DDD"
    foreground = "#333"
    workspace_background = "#EEE"
    workspace_foreground = "#AAA"
    workspace_full_background = "#CCC"
    workspace_full_foreground = "#333"
    workspace_focused_background = "#A1DFFF"
    workspace_focused_foreground = "#000"
    workspace_focused_full_background = "#46AAFE"
    workspace_focused_full_foreground = "#000"
    workspace_urgent_background = "#FFA040"
    workspace_urgent_foreground = "#000000"
    chart_background = "#EEE"
    chart_foreground = "#888"
    cpu_chart_line = "#F00"
    net_up_chart_line = "#0B0"
    net_down_chart_line = "#F00"
    volume_chart_background = "#AAA"


Colors = ColorsDark
